export const GET_ALL_CHARECTERS_BEGIN = "GET_ALL_CHARECTERS_BEGIN"
export const GET_ALL_CHARECTERS_SUCCESS = "GET_ALL_CHARECTERS_SUCCESS"
export const GET_ALL_CHARECTERS_FAILURE = "GET_ALL_CHARECTERS_FAILURE"
export const GET_ALL_CHARECTERS_DISMISS = "GET_ALL_CHARECTERS_DISMISS"